@echo off
echo Starting server...
start /B python src/app.py > server_log.txt 2>&1
echo Waiting for server to start...
timeout /t 5
echo Running verification...
python tests/verify_deployment.py > test_output.txt 2>&1
echo Done.
